# 03 - Federated Learning

## Defines

Define the available types of federated learning.

 - 'STRATIFIED': Stratified sampling of the data. The data is split into a number of shards, and each shard is assigned to a client. The data is split in a stratified manner, meaning that the distribution of the labels is approximately the same in each shard.
 - 'MISSING_1_ATTACK' - Each client is assigned a shard of data, each shard is missing one of the attack labels. Other clients in the network are exposed to the attack label, but the specific client is not. This demonstrates the ability of federated learning to protect against unknown attacks.
 - '1_ATTACK_ONLY' - Each client is assigned a shard of data, each shard contains only one of the attack labels.
 - 'HALF_BENIGN_ONLY' - Half of the clients are exposed to Benign data only, the other half are exposed to all data.


In [2]:
### THIS SECTION NEEDS TO BE SET TO DETERMINE WHICH CONFIGURATION METHOD TO UTILISE

SPLIT_AVAILABLE_METHODS = ['STRATIFIED','MISSING_1_ATTACK', '1_ATTACK_ONLY', 'HALF_BENIGN_ONLY' ]
METHOD = '1_ATTACK_ONLY'
NUM_OF_STRATIFIED_CLIENTS = 10  # only applies to stratified method
NUM_OF_ROUNDS = 10              # Number of FL rounds


The above test method in conjunction with the below classification selection will determine the number of clients.

EG: 
`STRATIFIED` with:
 - `ALL TYPES` - Results in `NUM_OF_STRATIFIED_CLIENTS` clients. Each client will have a stratified sample of the data.

`MISSING_1_ATTACK` with:
 - `individual_classifier` - Results in 33 clients. Each client will have benign traffic and 32 attack labels.
 - `group_classifier` - Results in 7 clients. Each client will have benign traffic and 6 attack groups.
 - `binary_classifier` - Results in 10 clients. Five clients will have benign traffic only and the other will have Benign and malicious attack labels.

`1_ATTACK_ONLY` with:
 - `individual_classifier` - Results in 33 clients. Each client will have benign traffic and 1 attack label.
 - `group_classifier` - Results in 7 clients. Each client will have benign traffic and 1 attack groups.
 - `binary_classifier` - Results in 10 clients. Five clients will have benign traffic only and the other will have Benign and malicious attack labels. - SAME AS MISSING_1_ATTACK for binary classifier

`HALF_BENIGN_ONLY` with:
 - `individual_classifier` - Results in 10 clients. Five clients will have benign traffic only and the other will have Benign and 33 malicious attack labels.
 - `group_classifier` - Results in 10 clients. Five clients will have benign traffic only and the other will have Benign and 7 malicious attack groups.
 - `binary_classifier` - Results in 10 clients. Five clients will have benign traffic only and the other will have Benign and malicious attack labels. - SAME AS MISSING_1_ATTACK for binary classifier


In [3]:
individual_classifier = False
group_classifier = True
binary_classifier = False


Include the defines for the dataframe columns and the attack labels and their mappings

In [4]:
from enum import Enum
from includes import *

##  Imports

In [5]:
%%capture
%pip install flwr[simulation] torch torchvision matplotlib sklearn openml

In [6]:
import os
import pandas as pd
import numpy as np
import flwr as fl
from tqdm import tqdm
import warnings
#warnings.filterwarnings('ignore')

import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms as transforms
from flwr.common import Metrics
from torch.utils.data import DataLoader, random_split


In [7]:
print("flwr", fl.__version__)
print("numpy", np.__version__)
print("torch", torch.__version__)

DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Training on {DEVICE}")

flwr 1.4.0
numpy 1.23.5
torch 2.0.1+cpu
Training on cpu


## Load the Dataset

In [8]:
DATASET_DIRECTORY = '../datasets/CICIoT2023/'

## Training data

Either read the training pickle file if it exists, or process the dataset from scratch.

In [9]:
# Check to see if the file 'training_data.pkl' exists in the directory. If it does, load it. If not, print an error.
if os.path.isfile('training_data.pkl'):
    print("File exists, loading data...")
    train_df = pd.read_pickle('training_data.pkl')
    print("Training data loaded from pickle file.")

else:
    df_sets = [k for k in os.listdir(DATASET_DIRECTORY) if k.endswith('.csv')]
    df_sets.sort()
    training_sets = df_sets[:int(len(df_sets)*.8)]
    test_sets = df_sets[int(len(df_sets)*.8):]

    # Print the number of files in each set
    print('Training sets: {}'.format(len(training_sets)))
    print('Test sets: {}'.format(len(test_sets)))

    ######################
    # HACK TEMP CODE
    ######################
    # Set training_sets to the last entry of training_sets
    training_sets = training_sets[-10:]
    print(f"HACK TO REPLICATE ORIGINAL AUTHORS CODE WITH ONE FILE TRAIN - {training_sets}")
    ######################
    # HACK END TEMP CODE
    ######################

    # Concatenate all training sets into one dataframe
    dfs = []
    print("Reading training data...")
    for train_set in tqdm(training_sets):
        df_new = pd.read_csv(DATASET_DIRECTORY + train_set)
        dfs.append(df_new)
    train_df = pd.concat(dfs, ignore_index=True)

    # Map y column to the dict_34_classes values - The pickle file already has this done.
    train_df['label'] = train_df['label'].map(dict_34_classes)

    # Save the output to a pickle file
    print("Writing training data to pickle file...")
    train_df.to_pickle('training_data.pkl')

print("Training data size: {}".format(train_df.shape))


File exists, loading data...
Training data loaded from pickle file.
Training data size: (27639635, 47)


In [10]:
train_df

flow_duration  Header_Length  Protocol Type  Duration          Rate  \
0              0.000000           1.23           1.05     65.74     15.152394   
1              0.351624       91157.50          17.00     64.00   5193.669702   
2              0.000000          54.00           6.00     64.00      0.333066   
3              0.000000           0.00           1.00     64.00     19.832584   
4             13.979960      573286.80           7.10    114.00     45.804266   
...                 ...            ...            ...       ...           ...   
27639630       0.000000          54.00           6.00     64.00     19.582485   
27639631       0.037146          78.22          36.21     63.18     24.542045   
27639632       3.293075     1025996.92          17.00     64.00    572.160392   
27639633       0.047343       35223.00          17.00     64.00  15083.107398   
27639634       0.000000           0.00           1.00     64.00      9.308130   

                 Srate  Drate  fin_flag_number  syn_flag_number  \
0            15.152394    0.0              0.0              0.0   
1          5193.669702    0.0              0.0              0.0   
2             0.333066    0.0              0.0              1.0   
3            19.832584    0.0              0.0              0.0   
4            45.804266    0.0              0.0              0.0   
...                ...    ...              ...              ...   
27639630     19.582485    0.0              0.0              0.0   
27639631     24.542045    0.0              0.0              0.0   
27639632    572.160392    0.0              0.0              0.0   
27639633  15083.107398    0.0              0.0              0.0   
27639634      9.308130    0.0              0.0              0.0   

          rst_flag_number  ...         Std  Tot size           IAT  Number  \
0                     0.0  ...    1.779972     42.81  8.312907e+07     9.5   
1                     0.0  ...    0.000000     50.00  8.301572e+07     9.5   
2                     0.0  ...    0.000000     54.00  8.309335e+07     9.5   
3                     0.0  ...    0.000000     42.00  8.312454e+07     9.5   
4                     0.0  ...  642.587064    789.20  1.948500e-03     5.5   
...                   ...  ...         ...       ...           ...     ...   
27639630              0.0  ...    0.000000     54.00  8.331443e+07     9.5   
27639631              0.0  ...  110.233513    453.78  8.358187e+07     9.5   
27639632              0.0  ...    0.000000    554.00  8.378910e+07     9.5   
27639633              0.0  ...    0.000000     50.00  8.309852e+07     9.5   
27639634              0.0  ...  536.729102    949.52  8.324966e+07     9.5   

           Magnitue      Radius     Covariance  Variance  Weight  label  
0          9.214917    2.523392      35.566706      0.09  141.55      6  
1         10.000000    0.000000       0.000000      0.00  141.55     13  
2         10.392305    0.000000       0.000000      0.00  141.55      3  
3          9.165151    0.000000       0.000000      0.00  141.55      6  
4         38.718463  908.755341  458960.956419      0.90   38.50      0  
...             ...         ...            ...       ...     ...    ...  
27639630  10.392305    0.000000       0.000000      0.00  141.55      2  
27639631  30.338676  154.660856   23401.960226      0.53  141.55     18  
27639632  33.286634    0.000000       0.000000      0.00  141.55     19  
27639633  10.000000    0.000000       0.000000      0.00  141.55      4  
27639634  45.017352  759.033957  306570.231772      0.94  141.55     10  

[27639635 rows x 47 columns]

---
## Test Data
Concat the test data into a single dataframe

In [11]:
# Check to see if the file 'test_data.pkl' exists in the directory. If it does, load it. If not, print an error.
testing_data_pickle_file = 'testing_data.pkl'

if os.path.isfile(testing_data_pickle_file):
    print(f"File {testing_data_pickle_file} exists, loading data...")
    test_df = pd.read_pickle(testing_data_pickle_file)
    print("Test data loaded from pickle file.")

else:
    print(f"File {testing_data_pickle_file} does not exist, constructing data...")

    df_sets = [k for k in os.listdir(DATASET_DIRECTORY) if k.endswith('.csv')]
    df_sets.sort()
    training_sets = df_sets[:int(len(df_sets)*.8)]
    test_sets = df_sets[int(len(df_sets)*.8):]

    ############################################
    ############################################
    # HACK - Make things quicker for now
    ############################################
    ############################################

    test_sets = df_sets[int(len(df_sets)*.95):]
    
    # Set training_sets to the last entry of training_sets
    test_sets = test_sets[-2:]
    
    ############################################
    ############################################
    # END HACK 
    ############################################
    ############################################

    # Print the number of files in each set
    print('Test sets: {}'.format(len(test_sets)))
    
    # Concatenate all testing sets into one dataframe
    dfs = []
    print("Reading test data...")
    for test_set in tqdm(test_sets):
        df_new = pd.read_csv(DATASET_DIRECTORY + test_set)
        dfs.append(df_new)
    test_df = pd.concat(dfs, ignore_index=True)

    # Map y column to the dict_34_classes values - The pickle file already has this done.
    test_df['label'] = test_df['label'].map(dict_34_classes)

    # Save the output to a pickle file
    print(f"Writing test data to pickle file {testing_data_pickle_file}...")
    test_df.to_pickle(testing_data_pickle_file)

print("Testing data size: {}".format(test_df.shape))

File testing_data.pkl exists, loading data...
Test data loaded from pickle file.
Testing data size: (462433, 47)


---
# Scale the test and train data

### Scale the training data input features

In [12]:
scaler = StandardScaler()
train_df[X_columns] = scaler.fit_transform(train_df[X_columns])

### Scale the testing data input features

In [13]:
test_df[X_columns] = scaler.fit_transform(test_df[X_columns])

---
# Define the classification problem - (2 classes, 8 classes or 34 classes)
Change the following cell to select the classification type

If the METHOD == STRATIFIED, then we can use any classifier
If the METHOD == ATTACK_GROUP then we must use Group Classifier.

In [14]:

class_size_map = {2: "Binary", 8: "Group", 34: "Individual"}

if group_classifier:
    print("Group 8 Class Classifier... - Adjusting labels in test and train dataframes")
    # Map y column to the dict_7_classes values
    test_df['label'] = test_df['label'].map(dict_8_classes)
    train_df['label'] = train_df['label'].map(dict_8_classes)
    class_size = "8"      
    
elif binary_classifier:
    print("Binary 2 Class Classifier... - Adjusting labels in test and train dataframes")
    # Map y column to the dict_2_classes values
    test_df['label'] = test_df['label'].map(dict_2_classes)
    train_df['label'] = train_df['label'].map(dict_2_classes)
    class_size = "2"

else:
    print ("Individual 34 Class classifier... - No adjustments to labels in test and train dataframes")
    class_size = "34"


Individual 34 Class classifier... - No adjustments to labels in test and train dataframes


---
# Split the Training Data into partitions for the Federated Learning clients depending on the test required
As a reminder:

`STRATIFIED` with:
 - `ALL TYPES` - Results in `NUM_OF_STRATIFIED_CLIENTS` clients. Each client will have a stratified sample of the data.

`MISSING_1_ATTACK` with:
 - `individual_classifier` - Results in 33 clients. Each client will have benign traffic and 32 attack labels.
 - `group_classifier` - Results in 7 clients. Each client will have benign traffic and 6 attack groups.
 - `binary_classifier` - Results in 10 clients. Five clients will have benign traffic only and the other will have Benign and malicious attack labels.

`1_ATTACK_ONLY` with:
 - `individual_classifier` - Results in 33 clients. Each client will have benign traffic and 1 attack label.
 - `group_classifier` - Results in 7 clients. Each client will have benign traffic and 1 attack groups.
 - `binary_classifier` - Results in 10 clients. Five clients will have benign traffic only and the other will have Benign and malicious attack labels. - SAME AS MISSING_1_ATTACK for binary classifier

`HALF_BENIGN_ONLY` with:
 - `individual_classifier` - Results in 10 clients. Five clients will have benign traffic only and the other will have Benign and 33 malicious attack labels.
 - `group_classifier` - Results in 10 clients. Five clients will have benign traffic only and the other will have Benign and 7 malicious attack groups.
 - `binary_classifier` - Results in 10 clients. Five clients will have benign traffic only and the other will have Benign and malicious attack labels. - SAME AS MISSING_1_ATTACK for binary classifier


In [15]:
from sklearn.model_selection import StratifiedKFold

# Define fl_X_train and fl_y_train
fl_X_train = []
fl_y_train = []

if METHOD == 'STRATIFIED':
    print(f"{Colours.YELLOW.value}STRATIFIED METHOD{Colours.NORMAL.value} with {class_size} class classifier")
    # We are going to split the training data into 'NUM_OF_STRATIFIED_CLIENTS' smaller groups using StratifiedKFold
    skf = StratifiedKFold(n_splits=NUM_OF_STRATIFIED_CLIENTS, shuffle=True, random_state=42)
    for train_index, test_index in skf.split(train_df[X_columns], train_df[y_column]):
        fl_X_train.append(train_df[X_columns].iloc[test_index])
        fl_y_train.append(train_df[y_column].iloc[test_index])

elif METHOD == 'MISSING_1_ATTACK':
    print(f"{Colours.YELLOW.value}MISSING_1_ATTACK METHOD{Colours.NORMAL.value} with {class_size} class classifier")

    if individual_classifier or group_classifier:
        # Set the number of splits required to the number of classes - 1
        num_splits = int(class_size) - 1
    else:
        # For binary classifier, set the number of splits to 10
        num_splits = 10

    skf = StratifiedKFold(n_splits=num_splits, shuffle=True, random_state=42)

    # When creating the clients, we will remove one attack class from the training data
    # For the binary classifier, evey other client will have the benign class removed
    for i, (train_index, test_index) in enumerate(skf.split(train_df[X_columns], train_df[y_column])):
        if binary_classifier:
            print(f"i: {i} = i % 2 = {i % 2}")
            if i % 2 == 0:
                print("Benign only")
                # Create a new dataframe for the client data with only benign traffic
                client_df = pd.concat([train_df.iloc[test_index][train_df[y_column] != 1]], ignore_index=True)
                fl_X_train.append(client_df[X_columns])
                fl_y_train.append(client_df[y_column])
            else:
                print("Both")
                # Create a new dataframe for the client data
                fl_X_train.append(train_df[X_columns].iloc[test_index])
                fl_y_train.append(train_df[y_column].iloc[test_index])
        else:
            # Create a new dataframe for the client data
            client_df = pd.concat([train_df.iloc[test_index][train_df[y_column] != i+1]], ignore_index=True)
            fl_X_train.append(client_df[X_columns])
            fl_y_train.append(client_df[y_column])

elif METHOD == '1_ATTACK_ONLY':
    print(f"{Colours.YELLOW.value}1_ATTACK_ONLY METHOD{Colours.NORMAL.value} with {class_size} class classifier")
    # Each client only has one attack class in their training data along with the Benign data
    
    if individual_classifier or group_classifier:
        # Set the number of splits required to the number of classes - 1
        num_splits = int(class_size) - 1
    else:
        # For binary classifier, set the number of splits to 10
        num_splits = 10

    skf = StratifiedKFold(n_splits=num_splits, shuffle=True, random_state=42)

    # When creating the clients, we will only add the benign data and the attack class for that client
    for i, (train_index, test_index) in enumerate(skf.split(train_df[X_columns], train_df[y_column])):
        if binary_classifier:
            print(f"i: {i} = i % 2 = {i % 2}")
            if i % 2 == 0:
                print("Benign only")
                # Create a new dataframe for the client data with only benign traffic
                client_df = pd.concat([train_df.iloc[test_index][train_df[y_column] != 1]], ignore_index=True)
                fl_X_train.append(client_df[X_columns])
                fl_y_train.append(client_df[y_column])
            else:
                print("Both")
                # Create a new dataframe for the client data
                fl_X_train.append(train_df[X_columns].iloc[test_index])
                fl_y_train.append(train_df[y_column].iloc[test_index])
        else:
            # Create a new dataframe for the client data
            client_df = pd.concat([train_df.iloc[test_index][(train_df[y_column] == 0) | (train_df[y_column] == i+1)]], ignore_index=True)
            fl_X_train.append(client_df[X_columns])
            fl_y_train.append(client_df[y_column])

elif METHOD == 'HALF_BENIGN_ONLY':
    print(f"{Colours.YELLOW.value}HALF_BENIGN_ONLY METHOD{Colours.NORMAL.value} with {class_size} class classifier")

    num_splits = 10

    # Split into 10 client data
    skf = StratifiedKFold(n_splits=NUM_OF_STRATIFIED_CLIENTS, shuffle=True, random_state=42)

    # For i % 2 == 0, add only benign data
    # For i % 2 == 1, add all data
    for i, (train_index, test_index) in enumerate(skf.split(train_df[X_columns], train_df[y_column])):
        if i % 2 == 0:
            print("Benign only")
            # Create a new dataframe for the client data with only benign traffic
            client_df = pd.concat([train_df.iloc[test_index][train_df[y_column] == 0]], ignore_index=True)
            fl_X_train.append(client_df[X_columns])
            fl_y_train.append(client_df[y_column])
        else:
            print("All Classes")
            fl_X_train.append(train_df[X_columns].iloc[test_index])
            fl_y_train.append(train_df[y_column].iloc[test_index])
else:
    print(f"{Colours.RED.value}ERROR: Method {METHOD} not recognised{Colours.NORMAL.value}")
    exit()



1_ATTACK_ONLY METHOD with 34 class classifier


C:\Users\jd7-white\AppData\Local\Temp\ipykernel_19572\338337730.py:79: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  client_df = pd.concat([train_df.iloc[test_index][(train_df[y_column] == 0) | (train_df[y_column] == i+1)]], ignore_index=True)
C:\Users\jd7-white\AppData\Local\Temp\ipykernel_19572\338337730.py:79: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  client_df = pd.concat([train_df.iloc[test_index][(train_df[y_column] == 0) | (train_df[y_column] == i+1)]], ignore_index=True)
C:\Users\jd7-white\AppData\Local\Temp\ipykernel_19572\338337730.py:79: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  client_df = pd.concat([train_df.iloc[test_index][(train_df[y_column] == 0) | (train_df[y_column] == i+1)]], ignore_index=True)
C:\Users\jd7-white\AppData\Local\Temp\ipykernel_19572\338337730.py:79: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  client_df = pd.concat([

In [16]:
NUM_OF_CLIENTS = len(fl_X_train)

for i in range(len(fl_X_train)):
    # Show the unique values in the y column
    (f"Client ID: {i}")
    print(f"fl_X_train[{i}].shape: {fl_X_train[i].shape}")  
    print(f"fl_y_train[{i}].value_counts():\n{fl_y_train[i].value_counts()}")
    print(f"fl_y_train[{i}].unique(): {fl_y_train[i].unique()}\n")


fl_X_train[0].shape: (92280, 46)
fl_y_train[0].value_counts():
1    72591
0    19689
Name: label, dtype: int64
fl_y_train[0].unique(): [1 0]

fl_X_train[1].shape: (93126, 46)
fl_y_train[1].value_counts():
2    73437
0    19689
Name: label, dtype: int64
fl_y_train[1].unique(): [2 0]

fl_X_train[2].shape: (92448, 46)
fl_y_train[2].value_counts():
3    72759
0    19689
Name: label, dtype: int64
fl_y_train[2].unique(): [3 0]

fl_X_train[3].shape: (116817, 46)
fl_y_train[3].value_counts():
4    97128
0    19689
Name: label, dtype: int64
fl_y_train[3].unique(): [0 4]

fl_X_train[4].shape: (100357, 46)
fl_y_train[4].value_counts():
5    80667
0    19690
Name: label, dtype: int64
fl_y_train[4].unique(): [5 0]

fl_X_train[5].shape: (148856, 46)
fl_y_train[5].value_counts():
6    129166
0     19690
Name: label, dtype: int64
fl_y_train[5].unique(): [6 0]

fl_X_train[6].shape: (84322, 46)
fl_y_train[6].value_counts():
7    64632
0    19690
Name: label, dtype: int64
fl_y_train[6].unique(): [7 0]

f

Prepare an output directory where we can store the results of the federated learning

In [17]:
# Create an "Output" directory if it doesnt exist already
if not os.path.exists("Output"):
    os.makedirs("Output")

sub_directory_name = f"Output/{METHOD}_Classifier-{class_size}_Clients-{NUM_OF_CLIENTS}_Rounds-{NUM_OF_ROUNDS}"

# Create an "Output/{METHOD}-{NUM_OF_CLIENTS}-{NUM_OF_ROUNDS}" directory if it doesnt exist already
if not os.path.exists(f"Output/{sub_directory_name}"):
    os.makedirs(f"Output/{sub_directory_name}")

# Ensure the directory is empty
for file in os.listdir(f"Output/{sub_directory_name}"):
    file_path = os.path.join(f"Output/{sub_directory_name}", file)
    if os.path.isfile(file_path):
        os.unlink(file_path)

# Original training size is the sum of all the fl_X_train sizes
original_training_size = 0
for i in range(len(fl_X_train)):
    original_training_size += fl_X_train[i].shape[0]

# Write this same info to the output directory/Class Split Info.txt
with open(f"Output/{sub_directory_name}/Class Split Info.txt", "w") as f:
    for i in range(len(fl_X_train)):
        f.write(f"Client ID: {i}\n")
        f.write(f"fl_X_train.shape: {fl_X_train[i].shape}\n")
        f.write(f"Training data used {original_training_size}")
        f.write(f"fl_y_train.value_counts():\n{fl_y_train[i].value_counts()}\n")
        f.write(f"fl_y_train.unique(): {fl_y_train[i].unique()}\n\n")

### Convert the training dataset

In [18]:
# Convert the testing daya to X_test and y_test ndarrays
X_test = test_df[X_columns].to_numpy()
y_test = test_df[y_column].to_numpy()

---
### Data check

In [19]:
print("NUM_CLIENTS:", NUM_OF_CLIENTS)

print("NUM_ROUNDS:", NUM_OF_ROUNDS)
print()


print("Original training size: {}".format(original_training_size))


print("Checking training data split groups")
for i in range(len(fl_X_train)):
    print(i, ":", "X Shape", fl_X_train[i].shape, "Y Shape", fl_y_train[i].shape)


# Print the sizes of X_test and y_test
print("\nChecking testing data")
print("X_test size: {}".format(X_test.shape))
print("y_test size: {}".format(y_test.shape))

print("\nDeploy Simulation")

NUM_CLIENTS: 33
NUM_ROUNDS: 10

Original training size: 1467635
Checking training data split groups
0 : X Shape (92280, 46) Y Shape (92280,)
1 : X Shape (93126, 46) Y Shape (93126,)
2 : X Shape (92448, 46) Y Shape (92448,)
3 : X Shape (116817, 46) Y Shape (116817,)
4 : X Shape (100357, 46) Y Shape (100357,)
5 : X Shape (148856, 46) Y Shape (148856,)
6 : X Shape (84322, 46) Y Shape (84322,)
7 : X Shape (24811, 46) Y Shape (24811,)
8 : X Shape (24841, 46) Y Shape (24841,)
9 : X Shape (27796, 46) Y Shape (27796,)
10 : X Shape (20106, 46) Y Shape (20106,)
11 : X Shape (20203, 46) Y Shape (20203,)
12 : X Shape (79245, 46) Y Shape (79245,)
13 : X Shape (56113, 46) Y Shape (56113,)
14 : X Shape (67603, 46) Y Shape (67603,)
15 : X Shape (20983, 46) Y Shape (20983,)
16 : X Shape (37490, 46) Y Shape (37490,)
17 : X Shape (33169, 46) Y Shape (33169,)
18 : X Shape (35654, 46) Y Shape (35654,)
19 : X Shape (19731, 46) Y Shape (19731,)
20 : X Shape (21456, 46) Y Shape (21456,)
21 : X Shape (21162, 4

----
# Federated Learning
## Import the libraries and print the versions

In [20]:
import os
import flwr as fl
import numpy as np
import tensorflow as tf

# Make TensorFlow log less verbose
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Dropout

label = train_df[y_column]

Define the Client and Server code

In [21]:
import os
import flwr as fl
import numpy as np
import tensorflow as tf

print('scikit-learn {}.'.format(sklearn.__version__))
print("flwr", fl.__version__)
print("numpy", np.__version__)
print("tf", tf.__version__)
# Make TensorFlow log less verbose
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Dropout

import datetime

client_evaluations = []

class NumpyFlowerClient(fl.client.NumPyClient):
    def __init__(self, cid, model, train_data, train_labels):
        self.model = model
        self.cid = cid
        self.train_data = train_data
        self.train_labels = train_labels

    def get_parameters(self, config):
        return self.model.get_weights()

    def fit(self, parameters, config):
        self.model.set_weights(parameters)
        print ("Client ", self.cid, "Training...")
        self.model.fit(self.train_data, self.train_labels, epochs=5, batch_size=32)
        print ("Client ", self.cid, "Training complete...")
        return self.model.get_weights(), len(self.train_data), {}

    def evaluate(self, parameters, config):
        self.model.set_weights(parameters)
        print ("Client ", self.cid, "Evaluating...")
        loss, accuracy = self.model.evaluate(self.train_data, self.train_labels, batch_size=32)
        print(f"{Colours.YELLOW.value}Client {self.cid} evaluation complete - Accuracy: {accuracy:.6f}, Loss: {loss:.6f}{Colours.NORMAL.value}")

        # Write the same message to the "Output/{cid}_Evaluation.txt" file
        with open(f"Output/{sub_directory_name}/{self.cid}_Evaluation.txt", "a") as f:
            f.write(f"{datetime.datetime.now()} - Client {self.cid} evaluation complete - Accuracy: {accuracy:.6f}, Loss: {loss:.6f}\n")

            # Close the file
            f.close()

        return loss, len(self.train_data), {"accuracy": accuracy}
    
    def predict(self, incoming):
        prediction = np.argmax( self.model.predict(incoming) ,axis=1)
        return prediction

def client_fn(cid: str) -> NumpyFlowerClient:
    """Create a Flower client representing a single organization."""

    # Load model
    #model = tf.keras.applications.MobileNetV2((32, 32, 3), classes=10, weights=None)
    #model.compile("adam", "sparse_categorical_crossentropy", metrics=["accuracy"])

    print ("Client ID:", cid)

    model = Sequential([
      #Flatten(input_shape=(79,1)),
      Flatten(input_shape=(fl_X_train[0].shape[1] , 1)),
      Dense(50, activation='relu'),  
      Dense(25, activation='relu'),  
      Dense(len(label.unique()), activation='softmax')
    ])
    
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

   
    partition_id = int(cid)
    X_train_c = fl_X_train[partition_id]
    y_train_c = fl_y_train[partition_id]

    # Create a  single Flower client representing a single organization
    return NumpyFlowerClient(cid, model, X_train_c, y_train_c)


from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
eval_count = 0

def get_evaluate_fn(server_model):
    global eval_count
    """Return an evaluation function for server-side evaluation."""
    # The `evaluate` function will be called after every round
    
    
    def evaluate(server_round, parameters, config):
        global eval_count
        
        # Update model with the latest parameters
        server_model.set_weights(parameters)
        print (f"Server Evaluating... Evaluation Count:{eval_count}")
        loss, accuracy = server_model.evaluate(X_test, y_test)
        
        y_pred = server_model.predict(X_test)
        print ("Prediction: ", y_pred, y_pred.shape)
        #cmatrix = confusion_matrix(y_test, np.rint(y_pred))
        #print ("confusion_matrix:", cmatrix, cmatrix.shape)
                        
        print(f"{Colours.YELLOW.value}Server evaluation complete - Accuracy: {accuracy:.4f}, Loss: {loss:.4f}{Colours.NORMAL.value}")

        # Write the same message to the "Output/Server_Evaluation.txt" file
        with open(f"Output/{sub_directory_name}/Server_Evaluation.txt", "a") as f:
            f.write(f"{datetime.datetime.now()} - {server_round} : Server evaluation complete - Accuracy: {accuracy:.4f}, Loss: {loss:.4f}\n")

            # Close the file
            f.close()
        
        np.save("y_pred-" + str(eval_count) + ".npy", y_pred)
        #np.save("cmatrix-" + str(eval_count) + ".npy", cmatrix)
        eval_count = eval_count + 1
        
        return loss, {"accuracy": accuracy}
    return evaluate



server_model = Sequential([
    #Flatten(input_shape=(79,1)),
    Flatten(input_shape=(fl_X_train[0].shape[1] , 1)),
    Dense(50, activation='relu'),  
    Dense(25, activation='relu'),  
    Dense(len(label.unique()), activation='softmax')
])


server_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Create FedAvg strategy
strategy = fl.server.strategy.FedAvg(
        fraction_fit=1.0,
        fraction_evaluate=0.5,
        min_fit_clients=2, #10,
        min_evaluate_clients=2, #5,
        min_available_clients=2, #10,
        evaluate_fn=get_evaluate_fn(server_model),
        #evaluate_metrics_aggregation_fn=weighted_average,
)

scikit-learn 1.2.2.
flwr 1.4.0
numpy 1.23.5
tf 2.12.0


In [22]:
%%time
print (f"{Colours.YELLOW.value}\nDeploy simulation... Method = {METHOD} - {class_size_map[len(label.unique())]} ({class_size}) Classifier")
print (f"Number of Clients = {NUM_OF_CLIENTS}\n")
print (f"Writing output to: {sub_directory_name}\n{Colours.NORMAL.value}")

# Output the same information to the Output/Run_details.txt file
with open(f"Output/{sub_directory_name}/Run_details.txt", "a") as f:
    f.write(f"{datetime.datetime.now()} - Deploy simulation... Method = {METHOD} - {class_size_map[len(label.unique())]} ({class_size}) Classifier\n")
    f.write(f"{datetime.datetime.now()} - Number of Clients = {NUM_OF_CLIENTS}\n")

    # Write Original train_df size
    f.write(f"{datetime.datetime.now()} - Original train_df size: {train_df.shape}\n")

    # Write the training data split groups
    for i in range(len(fl_X_train)):
        f.write(f"{datetime.datetime.now()} - {i}: X Shape {fl_X_train[i].shape}, Y Shape {fl_y_train[i].shape}\n")

    # Write the testing data
    f.write(f"{datetime.datetime.now()} - X_test size: {X_test.shape}\n")
    f.write(f"{datetime.datetime.now()} - y_test size: {y_test.shape}\n")
    
# close the file
f.close()

start_time = datetime.datetime.now()

# Start simulation
fl.simulation.start_simulation(
    client_fn=client_fn,
    num_clients=NUM_OF_CLIENTS,
    config=fl.server.ServerConfig(num_rounds=NUM_OF_ROUNDS),
    strategy=strategy,
)

end_time = datetime.datetime.now()
print("Total time taken: ", end_time - start_time)

print (f"{Colours.YELLOW.value} SIMULATION COMPLETE. Method = {METHOD} - {class_size_map[len(label.unique())]} ({class_size}) Classifier")
print (f"Number of Clients = {NUM_OF_CLIENTS}{Colours.NORMAL.value}\n")

# Output the same information to the Output/Run_details.txt file
with open(f"Output/{sub_directory_name}/Run_details.txt", "a") as f:
    f.write(f"{datetime.datetime.now()} - SIMULATION COMPLETE. Method = {METHOD} - {class_size_map[len(label.unique())]} ({class_size}) Classifier\n")
    f.write(f"{datetime.datetime.now()} - Total time taken: {end_time - start_time}\n")


Deploy simulation... Method = 1_ATTACK_ONLY - Individual (34) Classifier
Number of Clients = 33

Writing output to: Output/1_ATTACK_ONLY_Classifier-34_Clients-33_Rounds-10



INFO flwr 2023-07-09 20:19:06,192 | app.py:146 | Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
2023-07-09 20:19:12,154	INFO worker.py:1636 -- Started a local Ray instance.
INFO flwr 2023-07-09 20:19:15,324 | app.py:180 | Flower VCE: Ray initialized with resources: {'memory': 10073016731.0, 'node:127.0.0.1': 1.0, 'object_store_memory': 5036508364.0, 'CPU': 12.0, 'GPU': 1.0}
INFO flwr 2023-07-09 20:19:15,325 | server.py:86 | Initializing global parameters
INFO flwr 2023-07-09 20:19:15,326 | server.py:273 | Requesting initial parameters from one random client


(launch_and_get_parameters pid=17868) Client ID: 29


INFO flwr 2023-07-09 20:19:24,159 | server.py:277 | Received initial parameters from one random client
INFO flwr 2023-07-09 20:19:24,160 | server.py:88 | Evaluating initial parameters


Server Evaluating... Evaluation Count:0
14452/14452 [==============================] - 11s 736us/step


INFO flwr 2023-07-09 20:19:54,279 | server.py:91 | initial parameters (loss, other metrics): 3.738126277923584, {'accuracy': 0.0025560460053384304}
INFO flwr 2023-07-09 20:19:54,279 | server.py:101 | FL starting
DEBUG flwr 2023-07-09 20:19:54,279 | server.py:218 | fit_round 1: strategy sampled 33 clients (out of 33)


Prediction:  [[0.02470481 0.02321805 0.03336846 ... 0.03494521 0.03193658 0.02834002]
 [0.027416   0.02498446 0.02679003 ... 0.03263782 0.02393822 0.0264549 ]
 [0.0240427  0.02617874 0.02908646 ... 0.03284747 0.02487811 0.02589056]
 ...
 [0.02426193 0.02999595 0.03017696 ... 0.03350972 0.03048236 0.02836634]
 [0.02762228 0.02503138 0.02664964 ... 0.03295053 0.02382044 0.02626657]
 [0.01723263 0.01579125 0.03486866 ... 0.02040354 0.04012216 0.05560261]] (462433, 34)
Server evaluation complete - Accuracy: 0.0026, Loss: 3.7381
(launch_and_fit pid=17868) Client ID: 17
(launch_and_fit pid=17868) Client  17 Training...
(launch_and_fit pid=17868) Epoch 1/5
(launch_and_fit pid=17868) 
(launch_and_fit pid=17868)    1/1037 [..............................] - ETA: 19:50 - loss: 4.0752 - accuracy: 0.0000e+00
(launch_and_fit pid=17868)   29/1037 [..............................] - ETA: 1s - loss: 2.1810 - accuracy: 0.6056       
(launch_and_fit pid=17868)   61/1037 [>.............................] - 

DEBUG flwr 2023-07-09 20:22:29,827 | server.py:232 | fit_round 1 received 33 results and 0 failures
WARNING flwr 2023-07-09 20:22:29,895 | fedavg.py:243 | No fit_metrics_aggregation_fn provided


(launch_and_fit pid=17868) 4652/4652 [==============================] - 6s 1ms/step - loss: 8.1787e-04 - accuracy: 0.9999
(launch_and_fit pid=17868) Client  5 Training complete...
Server Evaluating... Evaluation Count:1
14452/14452 [==============================] - 13s 868us/step


INFO flwr 2023-07-09 20:23:03,899 | server.py:119 | fit progress: (1, 3.8918566703796387, {'accuracy': 0.023350410163402557}, 189.61373499999172)
DEBUG flwr 2023-07-09 20:23:03,899 | server.py:168 | evaluate_round 1: strategy sampled 16 clients (out of 33)


Prediction:  [[0.16851678 0.02060935 0.02757028 ... 0.02600607 0.03009353 0.02421103]
 [0.24896622 0.01485251 0.01986657 ... 0.03252234 0.01377155 0.01185298]
 [0.2827292  0.01299228 0.02218176 ... 0.02748846 0.01365479 0.01357764]
 ...
 [0.11585688 0.02576416 0.03224001 ... 0.03376355 0.02921583 0.01740208]
 [0.25003272 0.01487185 0.01962161 ... 0.03253409 0.01372547 0.01182252]
 [0.1817222  0.01459767 0.03586325 ... 0.01481242 0.02022082 0.03045096]] (462433, 34)
Server evaluation complete - Accuracy: 0.0234, Loss: 3.8919
(launch_and_evaluate pid=17868) Client ID: 7
(launch_and_fit pid=17868) 1217/4652 [======>.......................] - ETA: 4s - loss: 9.3688e-04 - accuracy: 1.0000 [repeated 2x across cluster]
(launch_and_fit pid=17868) 3716/4652 [======================>.......] - ETA: 1s - loss: 7.6498e-04 - accuracy: 1.0000 [repeated 4x across cluster]
(launch_and_fit pid=17868) 3871/4652 [=======================>......] - ETA: 1s - loss: 7.3437e-04 - accuracy: 1.0000 [repeated 4x 

(raylet) [2023-07-09 20:23:09,298 C 23652 24208] (raylet.exe) dlmalloc.cc:129:  Check failed: *handle != nullptr CreateFileMapping() failed. GetLastError() = 1450
(raylet) *** StackTrace Information ***
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) unknown
(raylet) configthreadlocale
(raylet) BaseThreadInitThunk
(raylet) RtlUserThreadStart
(raylet) 
ERROR flwr 2023-07-09 20:23:12,323 | ray_client_proxy.py:104 | The task's local raylet died. Check raylet.out for more information.
2023-07-09 20:23:23,837	WARNING worker.py:2019 -- The node with node id: 3f518b018058b4cdb9829bab9623bdc81f35fbb1ed38e47c1288ab77 and address: 127.0.0.1 and node 